# @package model
loss_cfg:
  caption_loss:
    reduction: weighted_sum
    use_logit_scale: true
  seg_loss:
    normalize_input: false
    text_clip_path: !!null
    loss_type: cross_entropy
    ignore_label: ${data.train_dataset.ignore_label}
    learnable_logit: false
  binary_loss: true
  weights:
    binary_loss: 1.0
    caption_loss: 0.5
    seg_loss: 1.0
  sync_dist: false
